### ISSUE TITLE
Question about separating senors

### ISSUE THREAD

**Issue by feeneyai** [StateFarm-STEM/hablogger#101]
One sensor we talked about adding was a display for checking to make sure all sensors are functioning as expected before the launch. I thought that could be a cool extension especially for AP CS A students that did this project last year in AP CS P.  I think I understood that can't be done with Arduinos because there is a memory issue on the Arduino board once all sensors are installed.  Would it be possible to split the sensors between 2 Arduinos and put displays on each board? I don't remember that they are necessarily tied to each other, but I guess they would be writing to the same SD card so maybe this could not work.

In our initial troubleshooting sessions, this could be a task some students "investigate" and report on after working with SF mentors that are intimately familiar with the payload, weights, power, etc. 

If it can be done then maybe the payload for NCHS AP CS A could incorporate that and students could be involved with how to get that added to the payload so it is programmed to report the important data, visible, working correctly, etc. The whole class would not work on that but maybe one or two of the groups that have either programmed a lot or did the project in AP CS Principles. I have many sharp students but one in particular that was a SF intern and his group is pretty advanced. 

Just a thought.

**Comment by pankonen** [comment]
I'll add this to our agenda when the core team meats about extras in each lab. Thanks for the input.

We have memory limitations currently but ran out of time trying to get it going on the Arduino. It is in [lab 7](https://github.com/StateFarm-STEM/hablogger/tree/main/python/raspberrypico/lesson-7) for Pico's though. The memory limitations come in with all the sensors in place. If its just the display it would work fine likely.

Personally I'd like to see it in the beginning so we see the output from each lab on the display (as well as the serial monitor in the IDE), that would be pretty cool.

**Comment by tdeknecht** [comment]
Thanks for the suggestion! It looks like Tom is on it.

For other suggestions and discussion related topics, please use the [Discussions](https://github.com/StateFarm-STEM/hablogger/discussions) feature in this project. We'll reserve the Issue board for features, enhancements, bugs, and other action items.

**Comment by pankonen** [comment]
Amy we talked last night when we met and will work on a display for both the Arduino and pico for minimum the last lesson but possibly for others to show debug info. Stay tuned. I'll link the issue to solve this when I create it.
