### ISSUE TITLE
Add Debugging to Python Lessons

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#121]
Add debugging to lesson code

**Comment by tdeknecht** [comment]
This is seemingly duplicate to https://github.com/StateFarm-STEM/hablogger/issues/62.

Similarly, the Troubleshooting section for each lesson is being improved over time as issues are uncovered. lesson 4's challenge introduces students to the Python Try Except code block. In later lessons, this code block exists to manage exceptions.

**Comment by pankonen** [comment]
The big one I'd like somewhere either in each python lesson (or linked in each) is the runtime or bios whatever that is loaded on the Pico to allow Python to run on it. I'd also like to see how to reset one that is having issues. I think Kevin has one we can use as an example in the STEM room.

**Comment by tdeknecht** [comment]
I ran into this with someone else and their Pico that might be having issues. I can reopen this issue, but I do wonder if this is outside the scope of the project.

Debugging a Pico, bootloading, using diagnostic pins... that's all available on the web and isn't necessary to launching a balloon to high altitude. If there are issues with a Pico, we're better off swapping it for a replacement and doing either our own diagnostic, or just replacing anew.
