### ISSUE TITLE
Lesson 1 (Introduction): Rewrite for Pico and MicroPython

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#2]
Change both lesson 1's to:

Move the HAB details [here](https://github.com/StateFarm-STEM/hablogger/tree/main/ballooninfo) and focus on familiarizing teams on:
- Components
- IDE
- Electronics basics

[Java / C](https://github.com/StateFarm-STEM/hablogger/tree/main/c/arduino/lesson1)
[Python](https://github.com/StateFarm-STEM/hablogger/tree/main/python/raspberrypico/lesson1)

**Comment by tdeknecht** [comment]
Hey fellas, I found the following steps and resources very quick to help me get set up with this project:

1. [Drag and Drop method for installing MicroPython on the pico](https://www.raspberrypi.com/documentation/microcontrollers/micropython.html#drag-and-drop-micropython)
2. [Set up Thonny to use the COM port for the Pico](https://core-electronics.com.au/guides/how-to-setup-a-raspberry-pi-pico-and-code-with-thonny/)

One thing to note is I'm on Windows for this. We might want to consider if users are on Mac, Ubuntu, Windows, or a Raspberry Pi when interfacing with the Pico.
