### ISSUE TITLE
Display module to see a system check and know the logger is working correctly

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#20]
We need a method to see if the HABlogger is working properly when flying. We will not be able to see console output in the field when we are loading the payload.

I have a pack of these [I2C OLED Display Modules](https://smile.amazon.com/gp/product/B08VNNCLHD/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1) we can test. I have sent some to the AZ crew for development. I will drop some by Trevor, Tyler, Jesse, etc this weekend.

We need to see that each device is working as expected:
- BMP is logging accurate data
- GPS is logging accurate data
- SD card is able to be written
  - Is it possible to see if data is written to the card

**Comment by tdeknecht** [comment]
Implemented via https://github.com/StateFarm-STEM/hablogger/pull/22

**Comment by tdeknecht** [comment]
Closed via https://github.com/StateFarm-STEM/hablogger/pull/22
