### ISSUE TITLE
Project Workbench prototyping

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#27]
We have been working on a design to contain the components, protect them from static, and ruggedize the project a bit.

[Project Workbench](https://github.com/StateFarm-STEM/hablogger/tree/main/project_workbench)

-	We need to add standoffs for each component. We only have the microcontrollers as I was out of kits with the original parts to give Carter for design
-	We need to modify the sd card compartment to allow the sd card to be removed and replaced by student when they do the labs and need to check data
-	We need to modify the cable wrap holders in the cable compartment, raise them up a bit for access
-	We are trying to determine how to latch it. Some ideas are being tested. Worse case we can use a latch from the hardware store.

Please provide feedback!

**Comment by tdeknecht** [comment]
How confident are we in the connections we'll be wiring up between the Pico and the modules? In other words, should we have a more permanent solution we use with confidence, potentially printing PCBs from a site like www.4pcb.com?

For the students we'll want them to wire things up and not have things permanently set (or have to deal with soldering/de-soldering). I think it'd be cool to have a couple rock-solid setups though to prove out our design overall.

**Comment by snarfattack** [comment]
I would recommend using the frog box style to start from and then divide it
up into part and item storage.

https://www.thingiverse.com/thing:4094861

**Comment by pankonen** [comment]
Going to print one here when I get a break in meetings! I just approved and merged your pull request Josh, thank you!

**Comment by pankonen** [comment]
These are complete! I've printed all of them for the student groups and will be assembling. I'm hoping the students will be using them Friday!

**Comment by pankonen** [comment]
Nicely done @snarfattack! Printed, assembled and delivered... almost. Kevin will be dropping normal west tomorrow.
