### ISSUE TITLE
Weather sensor update and challenges

### ISSUE THREAD

**Issue by gregdirst** [StateFarm-STEM/hablogger#3]
I was unable to find a library that works for the bmp180. However, I did end up getting the BMP280 built in library working with my Adafruit BMP280. Please let me know if anyone else has had better luck with the BMP180 as that is what we were previously using.

My BMP280 does not label the pins the same as most other devices. Most devices use SDA (data) and SCL (clock). However, the Adafruit BMP280 I have uses SDI (data) and SCK (clock).
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout/circuitpython-test

I had to learn how I2C works using only two wires, data and clock. It also took a while to figure out that there are challenges using two devices on the same wire. I started learning I2C using the LCD 2x16 module in a kit I purchased so when I tried to add the BMP280, everything I thought I understood about connecting an I2C device no longer worked. 

It wasn't until I watched a couple videos that I figured out there are 2 I2C channels (0 and 1). There are different SDA and SCL pins assigned to each one. I already placed the LCD on 0 and once I placed the BMP280 on 1 it came together.

There is more to learn about stop up resistors and how they allow multiple devices to work on the same channel.
https://www.youtube.com/watch?v=s7Lud1Gqrqw

Another challenge in general is understanding when to reboot the Pico. I still don't know exactly when I need to reboot it, but I decided to do it any time I get a runtime exception or the code breaks on a line that was previously working I click stop, reboot, then stop again, adjust the code, and run.

I also had to figure out that addressing is a critical piece (at least how I did it) to talking to a device. Care must be taken to ensure each device on a channel has a unique address. This is important when purchasing devices too.
LCD is 0x3F
BMP180 is 0x76
BMP280 is 0x77
It really helps to purchase devices that come with examples and libraries if they don't support built-in or common libraries.

I now have a working BMP280 and LCD screen displaying weather information.

**Comment by gregdirst** [comment]
LCD Module
[Freenove/Freenove_LCD_Module: Apply to FNK0079 (github.com)](https://github.com/Freenove/Freenove_LCD_Module/blob/main/Freenove_LCD_Module_for_Raspberry_Pi_Pico/Python/Python_Tutorial.pdf)

**Comment by gregdirst** [comment]
# ITS UGLY RIGHT NOW BECAUSE OF ALL THE TRIAL AND ERROR

# https://github.com/dafvid/micropython-bmp280

# import the required libraries
from bmp280 import *
from machine import Pin, I2C
import utime
from time import sleep
from I2C_LCD import I2CLcd

def check_devices(device_list):
    if devices == []:
        print("No i2c device !")
    else:
        print('i2c devices found:', len(device_list))
     
    for device in device_list:  
        print("Decimal address: ", device," | Hex address: ", hex(device))

# Initiate I2C 
i2c = I2C(0,           # positional argument - I2C id
          sda=Pin(4),  # named argument - serial data pin
          scl=Pin(5),  # named argument - serial clock pin
          freq=400000) # named argument - i2c frequency

# scan i2c port for available devices
devices = i2c.scan()

if devices != []:
    print("found LCD I2C address")
    check_devices(devices)
else:
    print("unable to find LCD I2C address")

lcd = I2CLcd(i2c, 0x3f, 2, 16)
lcd.move_to(0,0)
lcd.putstr("Weather Station")
lcd.move_to(0,1)
lcd.putstr("Raspberry PiPico")

# Initiate I2C 
i2c = I2C(1,              # positional argument - I2C id
          sda = Pin(10),   # named argument - serial data pin
          scl = Pin(11),   # named argument - serial clock pin
          freq = 1000000) # named argument - i2c frequency

# scan i2c port for available devices
devices = i2c.scan()

if devices != []:
    print("found BMP280 I2C address")
    check_devices(devices)
else:
    print("unable to find BMP280 I2C address")

# create a BMP 280 object
#bmp280_object = BMP280(i2c_object,
#                       addr = 0x77, # change it 
#                       use_case = BMP280_CASE_WEATHER)

# configure the sensor
# These configuration settings give most accurate values in my case
# tweak them according to your own requirements

bmp = BMP280(i2c, 0x77, use_case = BMP280_CASE_WEATHER)
# bmp.power_mode = BMP280_POWER_NORMAL
# bmp.oversample = BMP280_OS_HIGH
# bmp.temp_os = BMP280_TEMP_OS_8
# bmp.press_os = BMP280_TEMP_OS_4
# bmp.standby = BMP280_STANDBY_250
# bmp.iir = BMP280_IIR_FILTER_2

print("BMP Object created successfully !")
utime.sleep(2) # change it as per requirement
print("\n")

# Function for calculation altitude from pressure and temperature values
# because altitude() method is not present in the Library

def altitude_HYP(hPa , temperature):
    # Hypsometric Equation (Max Altitude < 11 Km above sea level)
    temperature = temperature
    local_pressure = hPa
    sea_level_pressure = 1013.25 # hPa      
    pressure_ratio = sea_level_pressure/local_pressure # sea level pressure = 1013.25 hPa
    h = (((pressure_ratio**(1/5.257)) - 1) * temperature ) / 0.0065
    return h


# altitude from international barometric formula, given in BMP 180 datasheet
def altitude_IBF(pressure):
    local_pressure = pressure    # Unit : hPa
    sea_level_pressure = 1013.25 # Unit : hPa
    pressure_ratio = local_pressure / sea_level_pressure
    altitude = 44330*(1-(pressure_ratio**(1/5.255)))
    return altitude

#sleep(2)
#lcd.clear()
while True:
    # accquire temperature value in celcius
    temperature_c = bmp.temperature # degree celcius
    
    # convert celcius to kelvin
    temperature_k = temperature_c + 273.15
    
    # accquire pressure value
    pressure = bmp.pressure  # pascal
    
    # convert pascal to hectopascal (hPa)
    # 1 hPa = 100 Pa
    # Therefore 1 Pa = 0.01 hPa
    pressure_hPa = ( pressure * 0.01 ) + ERROR # hPa
    
    # accquire altitude values from HYPSOMETRIC formula
    h = altitude_HYP(pressure_hPa, temperature_k)
    
    # accquire altitude values from International Barometric Formula
    altitude = altitude_IBF(pressure_hPa)
    press = "{:.2f}".format(pressure_hPa)
    h_alti = "{:.2f}".format(h)
    i_alti = "{:.2f}".format(altitude)
    print("Temperature : ",temperature_c," Degree Celcius")
    print("Pressure : ",pressure," Pascal (Pa)")
    print("Pressure : ",press," hectopascal (hPa) or millibar (mb)")
    print("Altitude (Hypsometric Formula) : ", h_alti ," meter")
    print("Altitude (International Barometric Formula) : ", i_alti ," meter")
    print("\n")
    #utime.sleep(1.5)
    
    lcd.move_to(0,0)
    lcd.putstr("Pico Weather Stn")
    lcd.move_to(0,1)
    lcd.putstr("                ")
    lcd.move_to(0,1)
    lcd.putstr("Temp: ")
    lcd.putstr(str(temperature_c))
    lcd.putstr(" C")
    sleep(1.5)
    lcd.move_to(0,1)
    lcd.putstr("                ")
    lcd.move_to(0,1)
    lcd.putstr("Press:")
    lcd.putstr(str (press))
    lcd.putstr(" hPa")
    sleep(1.5)
    lcd.move_to(0,1)
    lcd.putstr("                ")
    lcd.move_to(0,1)
    lcd.putstr("Alt: ")
    lcd.putstr(str (i_alti))
    lcd.putstr(" mtr")
    sleep(1.5)

**Comment by pankonen** [comment]
Hey @tdeknecht have a look at Greg's notes. @gregdirst Tyler picked up the BMP section when we met.

**Comment by tdeknecht** [comment]
@gregdirst , these findings and code provided relate to https://github.com/StateFarm-STEM/hablogger/issues/1. I suggest opening a pull request for that lesson if this is all working for the BMP280. That still leaves us with the BMP180, which might be preferred...? A decision needs to be made around which sensor we want to use given what you've found so far.

**Comment by gregdirst** [comment]
I have a branch on my machine after cloning the repo. Do I need to undo that and do a pull request instead? I am new at this Git stuff. I can only do simple things.

**Comment by pankonen** [comment]
Greg, I'm sorry I didn't finish clicking through the prompts when I added you to the repo. You should be able to accept the invitation and be good to go.

**Comment by pankonen** [comment]
I haven't (I should though) enabled merge approvals etc. yet. You can clone, make changes, push, commit, and merge. I have been using the desktop client on my Mac and honestly have t paid close attention to the details. That said it works really nice! Also, side note, if you install the GitHub app on your phone it will use that for mfa which is nice.

**Comment by tdeknecht** [comment]
> Ok, thanks @pankonen. However, after seeing the pull requests, I think I am doing it wrong the way I created my branch and want to push my changes up. Do I create a pull request? I haven't done them before.

You create a branch locally, make changes, push the branch up. That branch is something you work on, but other can collaborate if they decide to pull your branch local. Each time you make changes, follow  normal commit process and push your branch up. Sometimes you might have to sync up with `main` so you aren't behind `main` with any commits. When you are ready to merge your changes into `main`, open a Pull Request. Someone else will review the Pull Request, approve it, then you can merge it into `main`.

Functionally it's about the same as how GitLab works.

**Comment by gregdirst** [comment]
Sorry for being a pain and is very discouraging, but I have a branch named greg and I can pull, but cannot push. Here is what I get...

gregd@DESKTOP-M2BBE31 MINGW64 /F/Dev/git/hablogger/python/raspberrypico/lesson3 (greg)
$ git push --set-upstream origin greg
Enter passphrase for key '/f/Users/gregd/.ssh/id_rsa':
ERROR: Permission to StateFarm-STEM/hablogger.git denied to gregdirst.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

**Comment by tdeknecht** [comment]
@gregdirst try setting your remote to pulling over HTTPS instead of SSH. Do a `git remote set-url origin https://github.com/StateFarm-STEM/hablogger.git` in the project, then try pushing again.

**Comment by tdeknecht** [comment]
Closed via PI https://github.com/StateFarm-STEM/hablogger/pull/13
