### ISSUE TITLE
Library for SD Card

### ISSUE THREAD

**Issue by feeneyai** [StateFarm-STEM/hablogger#33]
I don't see which specific libary we should use for the SD Card Module

**Comment by tdeknecht** [comment]
Is this issue related to the Python code or C code?

If Python, I am using the driver located here: https://github.com/StateFarm-STEM/hablogger/blob/main/python/raspberrypico/drivers/src/sdcard.py

I pulled the driver local to the project to keep functionality consistent, and to avoid confusion with the instructors about which driver version to use from the open source project.

**Comment by feeneyai** [comment]
The C Code.  It says "using the SID library" in the lesson but when I go through Arduino's Library Manager to bring in the library there are some choices so I am not sure which to select.

**Comment by pankonen** [comment]
Hey @gregdirst can you have a look?

**Comment by gregdirst** [comment]
Can you provide a link to where you are seeing "using the SID library"

**Comment by gregdirst** [comment]
@feeneyai I think if you just add this to the top of your code it will know what you need...

```
#include <SPI.h>
#include <SD.h>
```

**Comment by pankonen** [comment]
I'm going to say this is fine as we completed the lesson last week and I ran through it at home with no issues with the fat client.
