### ISSUE TITLE
Lesson 3 - Suggestions

### ISSUE THREAD

**Issue by wardmr** [StateFarm-STEM/hablogger#46]
Hi there hablogger team. Thanks for all the work you have done with this. I just went through the raspberrypico lesson 3 and had some suggestions:

- Installing the driver was a little tricky and may create a lot of issues for students especially step 3. It may be my version or settings but stopping/refreshing did not make my raspberry pico folders show up on the left navigation. 
- Once stopping/refreshing and then clicking file>open, I then had the option of opening from computer or the raspberry pico. Clicking the raspberry pico pulls up a window that when right clicked gives the option for creating the new directory "drivers".
- Then when trying to save bmp180.py to pico, it does not give the option to save to computer or pico. Stopping/refreshing gave the option to open from the bmp180.py from the computer then stopping/refreshing again gave me the option to save the bmp180.py to the raspberry pico. I did it two different ways (in case students have more issues):
- Opening bmp180.py from computer and saving it to pico
- Copying and pasting the driver code into a new thonny file then saving to pico

I have a feeling if students solve this issue (or never have it) the lesson may be fairly quick. One thing that may be cool to add is an extra activity once they getting the readings here are my ideas:
-Students could concatenate the unit of measure to the end of the readings (rather than displayed at the front)
-Students could create a function inside the main entry point that will take in a measurement in meters and will return a value in feet (I know, imperial is gross but it could be a good exercise for students). Students can then call this function in the print statement on line 29 and pass through "altitude". Students should be able to figure this out eventually, but it has been about 6 months since they have seen functions in Python. Mentors/I can guide groups with this.

Sorry for the long issue... Hope it makes sense!

Note: I did it with a raspberry pico W

**Comment by TrevBart** [comment]
This is good feedback. I will add more to the steps to strengthen the driver installation.

I also like the stretch goals at the end as well. I will add some "things to try" at the bottom above the video walk-through.

Thank you!

**Comment by tdeknecht** [comment]
@TrevBart i use similar driver install steps in other lessons. We might be able to come up with something repeatable across all these lessons.

**Comment by feeneyai** [comment]
Hi Trevor, thank you for all you are doing!  This was something I was working on as well for Friday.  In the Arduino lesson the altitude is not written to the Serial Monitor so I thought it would be good to have the students do that.  You certainly don't have to include this but I wanted to have the students do a little more.  I think some will finish the lesson early so I was trying to think of something else they could do with this sensor.   

Extension - Lesson 3 - What is our Altitude?

In this extension you are going to measure our altitude and report it in the serial monitor.

You should have successfully wired the BMP_180 sensor to record the temperature in degrees Fahrenheit and the Barometric Pressure in inches of mercury (HG) to the Serial Monitor. 

What was the raw data from the BMP_180 for each of those? 

Did you cup your hands around the sensor and watch the temperature rise? Don't grab the sensor or press on it, gently cup your hands around it and it shouldn't take long to raise the temperature.
 
The BMP_180 also measures Altitude!  Add the appropriate code to capture the altitude and record the altitude in the Serial Monitor. Output the altitude after the other two measurements.  Look up to see what that number means.  Label the output appropriately. Just as the temperature was changed to a more common measure in the United States, change the Altitude to a more common measure in the United States.  Label the output appropriately. 

Raise your system, does the altitude change?

Look up to see what that number means and label the output appropriately.

What is the range of values for the altitude?  

Is the BMP_180 a good sensor for tracking a weather balloon for altitude?

You may want to slow down the output so it can be read more easily.

**Comment by wardmr** [comment]
I believe if I had view>files turned on before stopping/refreshing this could solve the problem I had.

**Comment by TrevBart** [comment]
This was great. I added sections on altitude for the Arduino and cleaned up the BMP library section. I have added more progress checks in the Python driver sections as well. I love thought starters and discussion so I added a "Want More" section to have the students try/think about/validate their understanding. I think it would be good to continue this in the next lessons as well. Please keep this feedback coming!
