### ISSUE TITLE
Arudino Lesson 3

### ISSUE THREAD

**Issue by feeneyai** [StateFarm-STEM/hablogger#47]
Isn't the video How to add an Adafruit library to the Arduino IDE specific to the Python?  The instructions in the tips are very clear how students are supposed to install the library for the Arduinos, I think having that link to the video could confuse students and they will try to download the library from Adafruit.

**Comment by feeneyai** [comment]
I think it may be good to move that video down under this line in Tips: If that doesn't work, you can install the BMP library [found here](https://learn.adafruit.com/bmp085/using-the-bmp085).  With that video being linked under Helpful Video Shortcuts it looks like it is something they are supposed to to get started rather than only do if there are problems with Manage Libraries.

**Comment by TrevBart** [comment]
I agree those links can be confusing. I have moved the manual library addition to the troubleshooting steps and commented out some of the others.

**Comment by TrevBart** [comment]
#49
