### ISSUE TITLE
Lesson 2 (Blinking Lights): Rewrite in MicroPython

### ISSUE THREAD

**Issue by tdeknecht** [StateFarm-STEM/hablogger#6]
Rewrite [Lesson 2 from pyinthesky project](https://github.com/StateFarm-STEM/pyinthesky/tree/main/lesson2) using MicroPython.

**Comment by tdeknecht** [comment]
@jessebaird , while tinkering from a learning standpoint, I was able to get the onboard LED to blink using this snippet:

```python
# Blinks onboard LED every 1 second

from machine import Pin
import time

led = Pin(25, Pin.OUT)

while True:
    led.toggle()
    time.sleep(1)
```

**Comment by pankonen** [comment]
Goals:

- Have LED's wired up on the breadboard 9they will need a resistor inline with each LED)
- Working code:
  - Flash each LED
  - Use variables to set time on
  - Use variable for pause between flashes
- Code is well commented explaining whats going on to help teachers work though on their time with the class
- Run from students USB port

Bonus:
- Troubleshooting steps

**Comment by jessebaird** [comment]
Also, since this is the first lesson, should I include how-tos on installing Micropython/Thonny or will this all be set up for them ahead of time?

**Comment by jessebaird** [comment]
One other question.  Will the kits that the students have include a breadboard?

**Comment by pankonen** [comment]
> @pankonen One other question. Will the kits that the students have include a breadboard?

yup, they will all have a kit with resistors, leds's, wires, breadboards, etc

**Comment by jessebaird** [comment]
I uploaded the files for various blinking LED options.  I will work on the instructions with pictures next.

**Comment by jessebaird** [comment]
I have completed the final draft of lesson 2, ready for review.  I'm happy to make tweaks as needed.

https://github.com/StateFarm-STEM/hablogger/tree/main/python/raspberrypico/lesson2
