### ISSUE TITLE
Lesson update for Python labs

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#62]
Guidance for troubleshooting thonny connection issues

- Check ports
- Ensure software is pushed to the Pico for initial startup (c or python version)
  - Instructions

**Comment by tdeknecht** [comment]
This issue is being address systematically through updates to each Python lesson when challenges are added. The existing Troubleshooting section in each lesson covers some cases, and more troubleshooting examples are being added as they are uncovered.
