### ISSUE TITLE
Lesson 4 (GPS Sensor): Rewrite in MicroPython

### ISSUE THREAD

**Issue by tdeknecht** [StateFarm-STEM/hablogger#7]
Rewrite [lesson 4 from pyinthesky](https://github.com/StateFarm-STEM/pyinthesky/tree/main/lesson4) in MicroPython with compatibility with the Pico

**Comment by pankonen** [comment]
Goals:

- Have GPS module wired up on the breadboard
- Working code echoing latitude, longitude, time
- Code is well commented explaining whats going on to help teachers work though on their time with the class
- Run from students USB port
Bonus:
- Troubleshooting steps

**Comment by tdeknecht** [comment]
Lesson 4 completed in this PR: https://github.com/StateFarm-STEM/hablogger/pull/14
