### ISSUE TITLE
Lesson 1 - order of install GIT and VSCode

### ISSUE THREAD

**Issue by SeanSchick** [StateFarm-STEM/hablogger#72]
The way it's laid out in lesson one you install VS Code after Git. But for the Git installer to use VS Code as the default editor, it needs to have VS Code there first. Otherwise Git won't let you select and continue the install

**Comment by pankonen** [comment]
Which lesson 1? i don't see either installing Git or VS Code?

**Comment by snarfattack** [comment]
This is in the c/pico version. Makes perfect sense.

As a reminder to myself, Tom found a new bundle from pi to setup the environment. So I need to review that too.

**Comment by pankonen** [comment]
> As a reminder to myself, Tom found a new bundle from pi to setup the environment. So I need to review that too.
https://www.raspberrypi.com/news/raspberry-pi-pico-windows-installer/

**Comment by tdeknecht** [comment]
I don't see VScode referenced in either Lesson 1 for either Arduino or Pico. It's possible this has been corrected via other lesson adjustments. Any thoughts before I close this down, @snarfattack @pankonen @TrevBart ?

**Comment by pankonen** [comment]
We can close this. Things have changed with how the pico works inside tooling. @snarfattack found we can run things as is on pico through Arduino studio and I think Thonny which wasn't the case before. Let's code this and address future work porting to Pico in other issues.
