### ISSUE TITLE
Lesson 6

### ISSUE THREAD

**Issue by feeneyai** [StateFarm-STEM/hablogger#73]
These suggestions could be part of the Troubleshooting section.

It would be good to remind the students of the three libraries in case they use a classroom laptop in which the libraries were not previously installed.  Or at least prompt them to look in the previous lessons to make sure they have all three libraries installed in the Arduino software. 

If a student writes a file to the SD card (so it ran successfully) and they want to make changes and run again, it may be good to remind students that they need to delete the .txt file written to the SD card if they want to run it again.

After I had everything connected and software running, one of the things that I experienced was not knowing if things were working while I was waiting for signal from the GPS sensor. There are the three initialization statements but nothing is output or written to the SD card or Serial Monitor unless the GPS sensor is actively acquiring a signal.  Another suggestion to Want More? would be to have the students print key things to the Serial Monitor so they can see progress. This does not write to the SD card but would help with monitoring progress. Suggestions "Temperature is " then temp, so they know it is operating while they wait to get GPS signal - it also would change while they walked around trying to get the GPS signal.  They could also add appropriate output statements like GPS Working - Satellites Not Found, GPS Working - Satellites found.

Just a couple suggestions.

**Comment by TrevBart** [comment]
@feeneyai these are good suggestions. I have updated the readme with your notes. I have added a constant "bypassGPS" to allow the write out even without GPS data. Thanks!
