### ISSUE TITLE
OLED Display

### ISSUE THREAD

**Issue by feeneyai** [StateFarm-STEM/hablogger#78]
Trevor and I have been playing around with the OLED display with the Arduinos. He output the temp from BMP and latitude and longitude to the GPS.  I think we should have our students wrap up this project with a Lesson 7 where the students program the BMP and GPS to show on the OLED display.  We would remove the SD card writer so that the Arduino can run the program - otherwise the file is too big.  I think the students would really like this.

**Comment by TrevBart** [comment]
@feeneyai I have a PR open for the code on Arduino. I am running low on time before vacation, so there is no video, but I have a cool extra activity for the students to load a custom image as a byte array and have the oLED display it. 😁 
https://www.instructables.com/How-to-Display-Images-on-OLED-Using-Arduino/

**Comment by feeneyai** [comment]
This looks great! I'll use this with the students, thanks for sharing!
