### ISSUE TITLE
Lesson 5 (SD Card Storage): Rewrite in MicroPython

### ISSUE THREAD

**Issue by tdeknecht** [StateFarm-STEM/hablogger#8]
Rewrite [lesson 5 from pyinthesky project](https://github.com/StateFarm-STEM/pyinthesky/tree/main/lesson5) using MicroPython and Pico compatibility

**Comment by pankonen** [comment]
Goals:

- Have SD card module wired up on the breadboard
- Working code writing / appending the CSV file every 30 seconds
- initialize the SD card, write a file, append to the file, close the SD card after each write
  - CSV file format is not important it can be random. When we do lesson 6 it will follow this format
    - temp, humidity, pressure, lat, long, alt, time
- Code is well commented explaining whats going on to help teachers work though on their time with the class
- Run from students USB port
Bonus:
- Troubleshooting steps

**Comment by tdeknecht** [comment]
@pankonen , what are the data formats for the following values (int, string, float, etc.)?

temp, humidity, pressure, lat, long, alt, time

**Comment by tdeknecht** [comment]
Implemented via https://github.com/StateFarm-STEM/hablogger/pull/12

**Comment by pankonen** [comment]
Temp two decimal places, humidity two decimal places, humidity two decimal places, lat 4 decimal places, long 4 decimal places, altitude two decimal places, time hh:mm:ss
