### ISSUE TITLE
Lesson 6 (All Together): Rewrite in MicroPython

### ISSUE THREAD

**Issue by tdeknecht** [StateFarm-STEM/hablogger#9]
Rewrite [lesson 6 in pyinthesky project](https://github.com/StateFarm-STEM/pyinthesky/tree/main/lesson6) in MicroPython with Pico compatibility

**Comment by pankonen** [comment]
Goals:

- Have all components wired up on the breadboard
  - Weather sensor, GPS, SD card
- Working code with enabling all sensors writing / appending the CSV file every 30 seconds
  - CSV file format:
    - temp, humidity, pressure, lat, long, alt, time
- Code is well commented explaining whats going on to help teachers work though on their time with the class
- Run from a battery like we would when we fly

**Comment by tdeknecht** [comment]
Lesson 6 added in PR https://github.com/StateFarm-STEM/hablogger/pull/15
